FROM dustynv/gstreamer:r36.2.0

RUN apt-get update && apt-get install -y git ffmpeg python3-opencv

RUN python3 -m pip install -U pip && python3 -m pip install ffmpeg-python

ARG CACHE=0
RUN git clone --depth 1 https://github.com/Salmon-Computer-Vision/salmon-computer-vision.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount

# Set working directory
WORKDIR /tools

CMD ["bash"]
