---
services:
  salmonmd:
    image: ${IMAGE_REPO_HOST}/salmoncounter:${TAG}
    env_file:
      - ./.env
    container_name: salmonmd
    network_mode: host
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USERNAME}/2024_test_vids:/app/2024_test_vids
      - ../../..:/tools
    runtime: nvidia
    command: >
      bash -c "cd /tools && python3 /tools/training/tools/run_motion_detect_rtsp.py ${FLAGS} --fps ${FPS} --test '${RTSP_URL}' \"${DRIVE}\""
