FROM dustynv/l4t-pytorch:r36.2.0

RUN python3 -m pip install -U pip

ARG CACHE=0
RUN git clone --depth 1 https://github.com/Salmon-Computer-Vision/salmon-computer-vision.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount
