FROM balenalib/raspberrypi-debian-node:buster-run

RUN python3 -m pip install -U pip

RUN git clone --depth 1 https://github.com/Salmon-Computer-Vision/salmon-computer-vision.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount
