FROM balenalib/raspberrypi5-python:3.11-bookworm-build

RUN apt-get update && apt-get install -y git ffmpeg python3-opencv

RUN python3 -m pip install -U pip && python3 -m pip install -U ffmpeg-python

ADD ./ /tools

RUN python3 -m pip install -e /tools/training/pysalmcount

# Set working directory
WORKDIR /tools

CMD ["bash"]
