FROM balenalib/raspberrypi3-python:3.7-buster-build

ARG OPENCV_VER="4.x"

RUN apt-get update
RUN apt-get install -y git

RUN apt-get install -y --no-install-recommends \
  gstreamer1.0-gl \
  gstreamer1.0-opencv \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-ugly \
  gstreamer1.0-tools \
  libgstreamer-plugins-base1.0-dev \
  libgstreamer1.0-0 \
  libgstreamer1.0-dev 
  
RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools wheel

RUN git clone --branch ${OPENCV_VER} --depth 1 --recurse-submodules --shallow-submodules https://github.com/opencv/opencv-python.git opencv-python-${OPENCV_VER}

RUN printf '[global]\nextra-index-url=https://www.piwheels.org/simple' > /etc/pip.conf

# OpenCV 4.x requires openssl 3.x
ARG OPENSSL_VER="openssl-3.3.1"

RUN git clone --branch ${OPENSSL_VER} --depth 1 https://github.com/openssl/openssl.git openssl-${OPENSSL_VER}
RUN cd openssl-${OPENSSL_VER} && ./Configure && make -j`nproc` && make test && make install
RUN ldconfig /usr/local/lib

ENV MAKEFLAGS="-j$(nproc)"

# Install OpenCV with gstreamer support
RUN cd opencv-python-${OPENCV_VER} && \
    export ENABLE_CONTRIB=0 && \
    export ENABLE_HEADLESS=1 && \
    export CMAKE_ARGS="-DWITH_GSTREAMER=ON" && \
    python3 -m pip wheel . --verbose && \
    python3 -m pip install opencv_python*.whl


RUN git clone --depth 1 https://github.com/Salmon-Computer-Vision/salmon-computer-vision.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount
