FROM balenalib/raspberrypi5-python:3.11-bookworm-build

RUN apt-get update && apt-get install -y --no-install-recommends \
    git ffmpeg python3-opencv \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U pip && python3 -m pip install -U ffmpeg-python

ARG USER=Salmon-Computer-Vision REPO=salmon-computer-vision BRANCH=master
ADD https://api.github.com/repos/${USER}/${REPO}/git/refs/heads/${BRANCH} version.json
RUN git clone --branch ${BRANCH} --depth 1 https://github.com/${USER}/${REPO}.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount

COPY run_all_videos.py /app/run_all_videos.py

# Set working directory
WORKDIR /tools

CMD ["bash"]
