FROM oceanaid/oceanaid-public:latest-jetpack6-opencv

# Install dependencies
RUN python3 -m pip install -U pip && \
    python3 -m pip install -U setuptools wheel check-wheel-contents packaging \
    watchdog lapx ffmpeg-python && \
    apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y ffmpeg cifs-utils

#RUN python3 -m pip uninstall -y torchvision && python3 -m pip install torchvision --index-url https://download.pytorch.org/whl/cu126

ARG USER=Salmon-Computer-Vision REPO=salmon-computer-vision BRANCH=master
ADD https://api.github.com/repos/${USER}/${REPO}/git/refs/heads/${BRANCH} version.json
RUN git clone --branch ${BRANCH} --depth 1 https://github.com/${USER}/${REPO}.git /tools

RUN python3 -m pip install -e /tools/training/pysalmcount

COPY watcher.py /app/watcher.py
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

WORKDIR /app
