FROM ultralytics/ultralytics:latest-jetson-jetpack6
ARG USER=Salmon-Computer-Vision REPO=salmon-computer-vision BRANCH=master

# Install dependencies
RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools wheel check-wheel-contents

ADD https://api.github.com/repos/${USER}/${REPO}/git/refs/heads/${BRANCH} version.json
RUN git clone --branch ${BRANCH} --depth 1 https://github.com/${USER}/${REPO}.git /tools

RUN python3 -m pip install /tools/training/pysalmcount

RUN python3 -m pip install watchdog lapx

COPY watcher.py /app/watcher.py

WORKDIR /app

# Start the watcher script
CMD ["python3", "watcher.py"]

