stages:
  update_raw:
    cmd: >-
      rclone sync 
      -P
      --filter "- /salm_dataset*/**"
      --filter "+ *.json"
      --filter "- *.zip"
      aws:salmonvision-ml-datasets/rgb/model_input/
      data/01_raw/labelstudio_annos
    outs:
      - data/01_raw/labelstudio_annos
  split_data:
    cmd: >-
      sleep 1
    deps:
      - data/01_raw/salmon_vid_counts.csv
      - data/01_raw/salmon_vid_counts_summary.csv
      - data/01_raw/sv_water_conditions
