stages:
  update_raw:
    cmd: >-
      rclone sync 
      -P
      --filter "- /salm_dataset*/**"
      --filter "+ *.json"
      --filter "- *.zip"
      aws:salmonvision-ml-datasets/rgb/raw/
      data/01_raw/labelstudio_annos
    deps:
      - s3://salmonvision-ml-datasets/rgb/raw
    outs:
      - data/01_raw/labelstudio_annos
    frozen: true
  build_model_input:
    cmd: >-
      scripts/yolo_converter_ls_video.py
      data/01_raw/labelstudio_annos
      --data-yaml config/salmon_yolo.yaml
      --out data/02_interim/yolo_annos
      --out-shards data/02_interim/yolo_annos
      --shard-size 100000
      --pattern '**/*.json'
      --include-sites tankeeah kitwanga bear
      --frame-stride 3
      --frame-offset-mode video_hash
    deps:
      - scripts/yolo_converter_ls_video.py
      - data/01_raw/labelstudio_annos
      - config/salmon_yolo.yaml
    outs:
      - data/02_interim/yolo_annos
  unpack_annos:
    cmd: >-
      scripts/unpack_annos.sh
      data/02_interim/yolo_annos
      data/02_interim/yolo_annos_unpacked
    deps:
      - data/02_interim/yolo_annos
  split_data:
    cmd: >-
      sleep 1
    deps:
      - data/01_raw/salmon_vid_counts.csv
      - data/01_raw/salmon_vid_counts_summary.csv
      - data/01_raw/sv_water_conditions
      - data/02_interim/yolo_annos_unpacked
