data:
  sites: tankeeah kitwanga bear kitkiata copper kwakwa Elbow koeye redoubt chignik
  neg: --include-negatives
  neg_ratio: 0.10
  neg_per_vid: 11
config:
  dataset: data/04_dataset
  yolo_workdir: data/04_dataset/salmon_dataset/yolo_workdir
  ray_tmp: /mnt/harukassd4tb/masamim
train:
  device: 2,3
exp:
  train_sites: tankeeah kitwanga bear
  val_sites: tankeeah kitwanga bear
  test_sites: tankeeah
eval:
  imgsz: 640
  batch: 32
  device: 2
  workers: 8
