data:
  sites: tankeeah kitwanga bear kitkiata copper kwakwa Elbow koeye redoubt 
    chignik klukshu
  neg_csvs: 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_tankeeah_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_bear_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_kitwanga_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_chignik_2024.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_copper_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_kitkiata_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_klukshu_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_koeye_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_redoubt_2025.csv 
    data/01_raw/sv_water_conditions/SV_conditions_tracking_tenas_2025.csv
  neg: --include-negatives
  neg_ratio: 0.10
  neg_per_vid: 11
  bucket: prod-salmonvision-edge-assets-labelstudio-source
config:
  dataset: data/04_dataset
  yolo_workdir: data/04_dataset/salmon_dataset/yolo_workdir
  ray_tmp: /mnt/harukassd4tb/masamim
tune:
  device: 0
  gpu_per_trial: 1 # Lower numbers creates more parallel trials (Can be fractional)
  batch: 32
  iterations: 20
train:
  device: 0
  batch: 32
  patience: 50
  tune_dir: tune15
exp:
  train_sites: tankeeah kitwanga bear kitkiata copper kwakwa Elbow koeye redoubt chignik
  val_sites: tankeeah kitwanga bear kitkiata copper kwakwa Elbow koeye redoubt chignik
  test_sites: chignik
eval:
  imgsz: 640
  batch: 32
  device: 0
  workers: 8
