data:
  sites: tankeeah kitwanga bear kitkiata copper kwakwa Elbow koeye redoubt chignik
train:
  sites: tankeeah kitwanga bear
test:
config:
  dataset: data/04_dataset
  yolo_workdir: data/04_dataset/salmon_dataset/yolo_workdir
  ray_tmp: /mnt/harukassd4tb/masamim
