---
services:
  syncing:
    build: 
      context: .
      dockerfile: Dockerfile-syncing-counts
      network: host
    container_name: syncing
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USERNAME}/.config/rclone/:/config/rclone/
    restart: always
    entrypoint: /bin/bash
    command: |
      /app/syncing.sh -s "${SITE_NAME}" -b "${BUCKET}" -o "${ORGID}" -d "${DRIVE}" -c /config/rclone/rclone.conf ${FLAGS}
  syncing-logs:
    build: 
      context: .
      dockerfile: Dockerfile-syncing-counts
      network: host
    container_name: syncing-logs
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USERNAME}/.config/rclone/:/config/rclone/
    restart: always
    entrypoint: /bin/sh
    command: |
      /app/syncing-logs.sh -s "${SITE_NAME}" -b "${BUCKET}" -o "${ORGID}" -d "${DRIVE}" -c /config/rclone/rclone.conf -t 8
