FROM dustynv/jetson-inference:r32.5.0

#RUN pip3 install scikit-build
#RUN wget https://github.com/Qengineering/TensorFlow-Addons-Jetson-Nano/raw/main/tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl && pip3 install tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl
#RUN apt install -y libffi-dev protobuf-compiler python3-pil python3-lxml python3-tk cmake python3-matplotlib
#RUN git clone --depth 1 https://github.com/Salmon-Computer-Vision/models.git /models

# Do `protoc` from `/models/research`
# Install prereqs of tensorflow from NVIDIA jetson nano doc
# Install `jp/v44 tensorflow==2.2.*` from NVIDIA jetson nano doc

# Install everything with jkjung-avt/tensorrt_demos instead
RUN apt-get update && apt-get install -y sudo protobuf-compiler libprotoc-dev python3-dev

RUN git clone https://github.com/jkjung-avt/tensorrt_demos.git /tensorrt_demos
WORKDIR /tensorrt_demos/ssd
RUN pip3 install protobuf && ./install_pycuda.sh && \
    pip3 install onnx==1.4.1

WORKDIR /tensorrt_demos/plugins
RUN make

WORKDIR /
